version: "3.8"

services:
  personal-development:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
      target: development
    image: personal-development
    ports:
      - "3002:3000"
    volumes:
      - ../../:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    env_file:
      - ../../.env.development
    command: npm run dev
