version: "3.8"

services:
  personal-development:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
      target: development
    image: personal-development
    ports:
      - "${PORT_EXTERNAL:-4000}:${PORT_INTERNAL:-3000}"
    volumes:
      - ../../:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - PORT_EXTERNAL=${PORT_EXTERNAL:-4000}
      - PORT_INTERNAL=${PORT_INTERNAL:-3000}
    env_file:
      - ../../.env.development
    command: npm run dev
