services:
  personal-production:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000}
    image: personal-production
    ports:
      - "3003:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
    env_file:
      - ../../.env.production
