services:
  personal-production:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000}
        NEXT_PUBLIC_DEFAULT_PROFILE_USERNAME: ${NEXT_PUBLIC_DEFAULT_PROFILE_USERNAME:-default}
    image: personal-production
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
      - NEXT_PUBLIC_DEFAULT_PROFILE_USERNAME=${NEXT_PUBLIC_DEFAULT_PROFILE_USERNAME:-default}
    env_file:
      - ../../.env.production
