version: "3.8"

services:
  personal-production:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: personal-production
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-https://api.production.example.com}
      - NEXT_PUBLIC_DEFAULT_PROFILE_USERNAME=${NEXT_PUBLIC_DEFAULT_PROFILE_USERNAME:-default}
    env_file:
      - ../../.env.production
    volumes:
      - ../../.env.production:/app/.env.production:ro
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
