services:
  personal-staging:
    build:
      context: ../../
      dockerfile: docker/staging/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000}
        NEXT_PUBLIC_DEFAULT_PROFILE_USERNAME: ${NEXT_PUBLIC_DEFAULT_PROFILE_USERNAME:-default}
    image: personal-staging
    container_name: personal-staging
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
      - NEXT_PUBLIC_DEFAULT_PROFILE_USERNAME=${NEXT_PUBLIC_DEFAULT_PROFILE_USERNAME:-default}
    env_file:
      - ../../.env.staging
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/",
        ]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    restart: unless-stopped
